name: Deploy to AWS Amplify

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-updates:
    runs-on: ubuntu-latest
    name: Deploying updates
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: testing_continuous_deployment
          fetch-depth: 0

      # Fix timestamps for aws sync to detect the correct changes
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Sync changes to AWS S3 Object
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          aws s3 sync --dryrun . s3://mycrcawsstaticwebsite01/site_frontend/ --exclude ".git/*"
          aws amplify start-deployment --app-id driozi76gdq9x --branch-name staging --source-url s3://mycrcawsstaticwebsite01/site_frontend/ --source-url-type BUCKET_PREFIX
