name: Deploy to AWS Amplify

on: workflow_dispatch

jobs:
  deploy-updates:
    runs-on: ubuntu-latest
    name: Deploying updates
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: testing_continuous_deployment

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Sync changes to AWS S3 Object
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pwd
          aws s3 sync --dryrun . s3://mycrcawsstaticwebsite01/site_frontend/ --exclude ".git/*" --exact-timestamps
